export type User = {
  uid: string;
  displayName: string | null;
  email: string | null;
};

export type Question = {
  question: string;
  options: string[];
  correctAnswer: string;
};

export type Quiz = {
  id?: string; // Made optional as it will be generated by Firestore
  title: string;
  topic: string;
  difficulty: 'easy' | 'medium' | 'hard';
  questions: Question[];
  authorId: string; // Changed from createdBy to match backend schema
  createdAt: string; // ISO date string
};

export type QuizAttempt = {
  id: string;
  quizId: string;
  quizTitle: string;
  userId: string;
  userName: string;
  answers: { [questionIndex: number]: string };
  score: number;
  startedAt: string;
  completedAt: string;
  violations: number;
  isFlagged: boolean;
};
