export type User = {
  uid: string;
  displayName: string | null;
  email: string | null;
};

export type Question = {
  question: string;
  options: string[];
  correctAnswer: string;
};

export type Quiz = {
  id?: string; // Made optional as it will be generated by Firestore
  title: string;
  topic: string;
  difficulty: 'easy' | 'medium' | 'hard';
  questions: Question[];
  authorId: string;
  createdAt: string; // ISO date string
};

export type QuizAttempt = {
  id: string; // UUID for the attempt
  quizId: string;
  quizTitle: string;
  userId: string; // ID of the user who took the quiz (or 'anonymous' for unauthenticated users)
  userName: string; // Display name (falls back to studentName for anonymous users)
  studentName: string; // Student's name (required for result tracking)
  registrationNumber: string; // Student's registration number (required for result tracking)
  authorId: string; // ID of the user who created the quiz
  answers: { [questionIndex: number]: string };
  score: number;
  startedAt: string;
  completedAt: string;
  violations: number;
  isFlagged: boolean;
};
